version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.3.0

    working_directory: ~/repo

    steps:
      - checkout

      # Install Ansible
      - run:
          name: Install Ansible
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            python3 -m pip -V
            python3 -m pip install --user ansible
            ansible --version

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Set up and start Docker service
      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Check DOCKER_PASSWORD
          command: echo -e $DOCKER_PASSWORD

      # Pull and Build Docker images
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_PAT | docker login -u $DOCKER_USERNAME --password-stdin https://index.docker.io/v1/
            docker pull rachelvf27/life2fullest-frontend:2
            docker build -t rachelvf27/life2fullest-frontend:2 -f client/frontend.dockerfile .
            docker pull rachelvf27/life2fullest-backend:2
            docker build -t rachelvf27/life2fullest-backend:2 -f backend.dockerfile .

      # Run Ansible playbooks (Provision Resources)
      - run:
          name: Run Ansible playbooks
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
            cd ansible
            ansible-playbook playbooks/networking.yml
            ansible-playbook playbooks/s3.yml
            ansible-playbook playbooks/dynamodb.yml
            ansible-playbook playbooks/ec2.yml
            ansible-playbook playbooks/elb.yml
            ansible-playbook playbooks/auto_scaling.yml

      # Run EKS Cluster (Deploy)
      - run:
          name: Run Ansible playbooks
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
            cd ansible
            ansible-playbook playbooks/eks_cluster.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build