version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.3.0

    working_directory: ~/repo

    steps:
      - checkout

      # Install Terraform
      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null
            sudo apt-get update && sudo apt-get install -y terraform
      
      # Install Ansible
      - run:
          name: Install Ansible
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            python3 -m pip -V
            python3 -m pip install --user ansible
            ansible --version

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Set up and start Docker service
      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Check DOCKER_PASSWORD
          command: echo -e $DOCKER_PASSWORD

      # Pull and Build Docker images
      - run:
          name: Build and push Docker image
          command: |
            echo $DOCKER_PAT | docker login -u $DOCKER_USERNAME --password-stdin https://index.docker.io/v1/
            docker pull rachelvf27/life2fullest-frontend:2
            docker build -t rachelvf27/life2fullest-frontend:2 -f client/frontend.dockerfile .
            docker pull rachelvf27/life2fullest-backend:2
            docker build -t rachelvf27/life2fullest-backend:2 -f backend.dockerfile .

      - run:
          name: Debug workspace directory structure
          command: |
            ls -R
            ls ansible/playbooks

      - run:
          name: Check AWS Keys
          command: |
            echo -e $AWS_ACCESS_KEY
            echo -e $AWS_SECRET_KEY

      # Run Ansible playbooks (Provision Resources)
      - run:
          name: Run Ansible playbooks
          command: |
            export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
            export AWS_SECRET_KEY=$AWS_SECRET_KEY
            cd ansible/playbooks
            pwd
            cp ../../terraform/{provider.tf,variables.tf} ../../terraform/networking/
            cp ../../terraform/{provider.tf,variables.tf} ../../terraform/s3/
            cp ../../terraform/{provider.tf,variables.tf} ../../terraform/dynamodb/
            cp ../../terraform/{provider.tf,variables.tf} ../../terraform/ec2/
            cp ../../terraform/{provider.tf,variables.tf} ../../terraform/elb/
            cp ../../terraform/{provider.tf,variables.tf} ../../terraform/auto_scaling/
            ansible-playbook networking.yml
            ansible-playbook s3.yml
            ansible-playbook dynamodb.yml
            ansible-playbook ec2.yml
            ansible-playbook elb.yml
            ansible-playbook auto_scaling.yml

      # Run EKS Cluster (Deploy)
      - run:
          name: Run Ansible playbooks
          command: |
            export AWS_ACCESS_KEY=$AWS_ACCESS_KEY
            export AWS_SECRET_KEY=$AWS_SECRET_KEY
            cd ansible
            ansible-playbook playbooks/eks_cluster.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build