apiVersion: v1
kind: Service
metadata:
  name: life2fullest-backend-service
  namespace: e-com-app-eks-cluster-app
  labels:
    app: life2fullest-backend
spec:
  selector:
    app: life2fullest-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
