apiVersion: apps/v1
kind: Deployment
metadata:
  name: life2fullest-frontend-deployment
  namespace: e-com-app-eks-cluster-app
  labels:
    app: life2fullest-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: life2fullest-frontend
  template:
    metadata:
      labels:
        app: life2fullest-frontend
    spec:
      affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - arm64
      containers:
      - name: life2fullest-frontend
        image: rachelvf27/life2fullest-frontend:latest
        ports:
        - containerPort: 8080
        resources:
            requests: # Minimum resources required
              memory: "128Mi"
              cpu: "250m"
            limits: # Maximum resources that can be used
              memory: "512Mi"
              cpu: "500m"
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
