- name: Provision new DynamoDb Tables
  hosts: localhost
  tasks:
    - name: Run terraform init for dynamoDb
      command: terraform init
      args:
        chdir: "{{ playbook_dir }}/../terraform/dynamoDb"

    - name: Run terraform plan for dynamoDb
      command: terraform plan
      args:
        chdir: "{{ playbook_dir }}/../terraform/dynamoDb"

    - name: Run terraform apply for dynamoDb
      command: terraform apply -auto-approve 
      args:
        chdir: "{{ playbook_dir }}/../terraform/dynamoDb"