- name: Provision EKS Cluster
  hosts: localhost
  tasks:
    - name: Run terraform init for EKS Cluster
      command: terraform init
      args:
        chdir: "{{ playbook_dir }}/../terraform"

    - name: Run terraform plan for EKS Cluster
      command: terraform plan
      args:
        chdir: "{{ playbook_dir }}/../terraform"

    - name: Run terraform apply for EKS Cluster
      command: terraform apply -auto-approve 
      args:
        chdir: "{{ playbook_dir }}/../terraform"