- name: Provision Application Load Balancer and Target Groups
  hosts: localhost
  tasks:
    - name: Run terraform init for elb
      command: terraform init
      args:
        chdir: "{{ playbook_dir }}/../../terraform/elb"

    - name: Run terraform plan for elb
      command: terraform plan
      args:
        chdir: "{{ playbook_dir }}/../../terraform/elb"

    - name: Run terraform apply for elb
      command: terraform apply -auto-approve 
      args:
        chdir: "{{ playbook_dir }}/../../terraform/elb"