- name: Provision AWS Networking resources
  hosts: localhost
  tasks:
    - name: Print the working directory
      command:
        cmd: ls

    - name: Run terraform init for Networking resources
      command: terraform init
      args:
        chdir: "{{ ansible_env.HOME }}/repo/terraform/networking"

    - name: Run terraform plan for Networking resources
      command: terraform plan
      args:
        chdir: "{{ ansible_env.HOME }}/repo/terraform/networking"

    - name: Run terraform apply to create networking infrastructure
      command: terraform apply -auto-approve
      args:
        chdir: "{{ ansible_env.HOME }}/repo/terraform/networking"
