- name: Provision AWS Networking resources
  hosts: localhost
  become: true
  tasks:
    - name: Print the current working directory
      command: pwd
      register: pwd_output

    - debug:
        var: pwd_output.stdout

    - name: Copy variables.tf to networking directory
      command: cp {{ playbook_dir }}/../../terraform/networking/variables.tf {{ playbook_dir }}/../../terraform/networking/

    - name: Run terraform init for Networking resources
      command: >
        bash -c "cd {{ playbook_dir }}/../../terraform/networking && pwd && terraform init"

    - name: Run terraform plan for Networking resources
      command: >
        bash -c "cd {{ playbook_dir }}/../../terraform/networking && pwd && terraform plan"

    - name: Run terraform apply to create networking infrastructure
      command: >
        bash -c "cd {{ playbook_dir }}/../../terraform/networking && pwd && terraform apply -auto-approve"
