- name: Provision AWS Networking resources
  hosts: localhost
  become: true
  tasks:
    - name: Print the current working directory
      command: pwd
      register: pwd_output

    - debug:
        var: pwd_output.stdout

    - name: Convert variables.tf from HCL to JSON
      command: hcl2json "{{ playbook_dir }}/../../terraform/networking/variables.tf"
      register: hcl2json_output
      changed_when: false
      failed_when: false

    - name: Include variables from variables.json
      include_vars:
        yaml: "{{ hcl2json_output.stdout | from_json | to_yaml }}"
      when: hcl2json_output.stdout is defined

    - name: Run terraform init for Networking resources
      command: >
        bash -c "cd {{ playbook_dir }}/../../terraform/networking && pwd && terraform init"
      register: init_output
      changed_when: false

    - name: "Display output: Terraform init"
      debug:
        msg: "{{ init_output.stdout }}"
      when: init_output.stdout is defined

    - name: Run terraform plan for Networking resources
      command: >
        bash -c "cd {{ playbook_dir }}/../../terraform/networking && pwd && terraform plan"
      register: plan_output
      changed_when: false

    - name: "Display output: Terraform plan"
      debug:
        msg: "{{ plan_output.stdout }}"
      when: plan_output.stdout is defined

    - name: Run terraform apply to create networking infrastructure
      command: >
        bash -c "cd {{ playbook_dir }}/../../terraform/networking && pwd && terraform apply -auto-approve"
      register: apply_output
      changed_when: false

    - name: "Display output: Terraform apply"
      debug:
        msg: "{{ apply_output.stdout }}"
      when: apply_output.stdout is defined
