- name: Provision new S3 bucket
  hosts: localhost
  tasks:
    - name: Run terraform init for S3
      command: terraform init
      args:
        chdir: "{{ playbook_dir }}/../terraform/s3"

    - name: Run terraform plan for S3
      command: terraform plan
      args:
        chdir: "{{ playbook_dir }}/../terraform/s3"

    - name: Run terraform apply for S3
      command: terraform apply -auto-approve 
      args:
        chdir: "{{ playbook_dir }}/../terraform/s3"